plugins {
  id 'com.enonic.xp.app'
  id 'com.github.node-gradle.node' version '7.1.0'
}

dependencies {
  include "com.enonic.xp:lib-portal:${xpVersion}"
  include "com.enonic.xp:lib-event:${xpVersion}"
  include "com.enonic.xp:lib-websocket:${xpVersion}"

  // https://market.enonic.com/vendors/enonic/graphql-lib
  include 'com.enonic.lib:lib-graphql:3.0.0'

  // https://market.enonic.com/vendors/enonic/mustache-lib
  include 'com.enonic.lib:lib-mustache:3.0.0'

  // https://market.enonic.com/vendors/enonic/static-asset-lib
  include 'com.enonic.lib:lib-static:3.0.0'

  // https://market.enonic.com/vendors/enonic/router-lib
  include 'com.enonic.lib:lib-router:4.0.0'
}

repositories {
  mavenLocal()
  mavenCentral()
  xp.enonicRepo()
}

node {
  // Whether to download and install a specific Node.js version or not
  // If false, it will use the globally installed Node.js
  // If true, it will download node using above parameters
  // Note that npm is bundled with Node.js
  download = true

  // Version of node to download and install (only used if download is true)
  // It will be unpacked in the workDir
  version = '24.11.0'
}

processResources {
  exclude '**/.gitkeep'
  exclude '**/*.json'
  exclude '**/*.ts'
  exclude '**/*.tsx'
  exclude '**/*.less'
}

tasks.register('npmBuild', NpmTask) {
  args = [
    'run',
    '--silent',
    'build'
  ]
  dependsOn npmInstall
  environment = [
    'FORCE_COLOR': 'true',
    'LOG_LEVEL_FROM_GRADLE': gradle.startParameter.logLevel.toString(),
    'NODE_ENV': project.hasProperty('dev') || project.hasProperty('development') ? 'development' : 'production'
  ]
  inputs.dir 'src/main/resources'
  inputs.file 'tsdown.config.ts'
  outputs.dir 'build/resources/main'
  outputs.upToDateWhen { false }
}

jar.dependsOn npmBuild

tasks.register('npmCheck', NpmTask) {
  dependsOn npmInstall
  args = [
    'run',
    'check'
  ]
  environment = [
    'FORCE_COLOR': 'true',
  ]
}

check.dependsOn npmCheck

tasks.register('npmTest', NpmTask) {
  args = [
    'run',
    'test'
  ]
  dependsOn npmInstall
  environment = [
    'FORCE_COLOR': 'true',
  ]
  inputs.dir 'src/jest'
  outputs.dir 'coverage'
  outputs.upToDateWhen { false }
}

test.dependsOn npmTest

tasks.withType(Copy).configureEach {
  includeEmptyDirs = false
}

jar {
  outputs.dir layout.buildDirectory.dir( "resources/main" )
}
